import chromadb


class ChromaVectorStore:
    """
    Persistent vector store using ChromaDB.

    Embeddings are generated by the embedding model passed
    to this class.
    """

    def __init__(
        self,
        embedder,
        persist_directory="./chroma_db",
        collection_name="real_estate_documents",
    ):
        self.embedder = embedder

        self.client = chromadb.PersistentClient(
            path=persist_directory
        )

        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"},
        )

    def add(self, documents):
        if not documents:
            return

        ids = []
        texts = []
        embeddings = []
        metadatas = []

        for doc in documents:
            document_id = f"{doc['source']}_{doc['chunk_id']}"

            ids.append(document_id)
            texts.append(doc["text"])

            embeddings.append(
                self.embedder.embed(doc["text"])
            )

            metadatas.append(
                {
                    "source": doc["source"],
                    "chunk_id": doc["chunk_id"],
                }
            )

        self.collection.upsert(
            ids=ids,
            documents=texts,
            embeddings=embeddings,
            metadatas=metadatas,
        )

    def search(self, query, top_k=4):
        query_embedding = self.embedder.embed(query)

        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=top_k,
        )

        output = []

        documents = results["documents"][0]
        metadatas = results["metadatas"][0]
        distances = results["distances"][0]

        for text, metadata, distance in zip(
            documents,
            metadatas,
            distances,
        ):
            output.append(
                {
                    "text": text,
                    "source": metadata["source"],
                    "chunk_id": metadata["chunk_id"],
                    "distance": distance,
                }
            )

        return output