"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { useSession } from "@/components/SessionProvider";
import { PropertyCard } from "@/components/PropertyCard";
import { Empty, ErrorNotice, Loading } from "@/components/States";
import type { Property, SearchFilters } from "@/types/api";

export default function Properties(){const {customer}=useSession();const [rows,setRows]=useState<Property[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError("");const d=new FormData(e.currentTarget);const body:SearchFilters={customer_id:customer?.customer_id,limit:20};for(const key of ["city","area","property_type","purpose"] as const){const v=String(d.get(key)||"");if(v)body[key]=v}for(const key of ["budget_max","bedrooms"] as const){const v=String(d.get(key)||"");if(v)body[key]=Number(v)}try{setRows(await api.searchProperties(body))}catch(e){setError(e instanceof ApiError?e.message:"Could not search properties.")}finally{setBusy(false)}};return <><div className="page-title"><span className="eyebrow">PROPERTY SEARCH</span><h1>Explore Properties</h1><p>Find homes and investment opportunities that match your location, budget, and preferences.</p></div><form className="search-bar" onSubmit={submit}><input name="city" placeholder="City"/><input name="area" placeholder="Area"/><input name="budget_max" type="number" min="0" placeholder="Maximum budget"/><input name="bedrooms" type="number" min="0" placeholder="Beds"/><select name="property_type"><option value="">Any type</option>{["Apartment","House","Villa","Plot","Commercial"].map(x=><option key={x}>{x}</option>)}</select><select name="purpose"><option value="">Any purpose</option>{["purchase","rental","investment","commercial"].map(x=><option key={x}>{x}</option>)}</select><button className="primary">Search</button></form>{busy&&<Loading label="Searching verified properties…"/>}{error&&<ErrorNotice message={error}/>} {rows?.length===0&&<Empty title="No verified matches" text="Try a broader city, area, budget or property type."/>}<div className="property-grid">{rows?.map(x=><PropertyCard key={x.property_id} property={x}/>)}</div></>}
