"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { useSession } from "@/components/SessionProvider";

export default function Home() { const {customer,ready}=useSession(); const router=useRouter(); const [healthy,setHealthy]=useState<boolean|null>(null); useEffect(()=>{if(ready&&!customer)router.replace("/start");api.getHealth().then(x=>setHealthy(x.database==="ok")).catch(()=>setHealthy(false));},[ready,customer,router]); return <><section className="hero"><div><span className="eyebrow">SMARTER PROPERTY DISCOVERY</span><h1>Find a place that<br/><em>fits your life.</em></h1><p>Explore verified properties and discover recommendations tailored to what you’re looking for.</p><div className="hero-actions"><Link className="button primary" href="/properties">Find properties</Link><Link className="button ghost" href="/recommendations">View recommendations</Link></div></div><div className="hero-art"><div className="arch"><span>SARA</span><b>Real Estate<br/> Assistant</b></div></div></section><div className="section-head"><div><small>YOUR PROPERTY JOURNEY
</small><h2>Continue your search</h2></div><span className={healthy?"health ok":"health"}>{healthy===null?"Checking backend":healthy?"Backend connected":"Backend unavailable"}</span></div><section className="dashboard-grid">{[["01","Explore Properties","Search verified properties by city, budget, property type, bedrooms, and more.","/properties"],["02","Recommended for You","Discover properties ranked around your saved preferences and interests.","/recommendations"],["03","Your Preferences","Refine location, budget and home requirements.","/preferences"],["04","Property Visits","View, schedule, reschedule, or cancel your property visits.","/appointments"]].map(([n,t,d,h])=><Link className="dashboard-card" href={h} key={t}><span>{n}</span><h3>{t}</h3><p>{d}</p><b>Open →</b></Link>)}</section></>; }
